/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Activation ou désactivation d'un pack pour un enfant.
 */
export interface AccessUpdate {
  enabled: boolean;
}
