/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Résultat de l'acceptation : nombre d'enfants nouvellement accessibles.
 */
export interface AcceptResponse {
  granted: number;
}
