/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PackSummary } from "./packSummary";

/**
 * Une ligne de liste blanche : ce pack est (ou a été) activé pour cet enfant.

``enabled_by`` est exposé parce qu'un enfant peut avoir plusieurs adultes
responsables : le co-parent doit voir qui a activé quoi.
 */
export interface AccessEntry {
  pack_id: string;
  enabled: boolean;
  enabled_by?: string | null;
  enabled_at?: string | null;
  updated_at?: string | null;
  pack: PackSummary;
}
