/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Rareté des achievements
 */
export type AchievementRarity =
  (typeof AchievementRarity)[keyof typeof AchievementRarity];

export const AchievementRarity = {
  common: "common",
  rare: "rare",
  epic: "epic",
  legendary: "legendary",
} as const;
