/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AchievementRarity } from "./achievementRarity";

/**
 * Schéma pour un achievement
 */
export interface AchievementResponse {
  id: string;
  name: string;
  description?: string | null;
  icon?: string | null;
  rarity: AchievementRarity;
  category?: string | null;
}
