/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { RecentLogin } from "./recentLogin";

/**
 * Métriques opérationnelles du tableau de bord admin.
 */
export interface AdminOverview {
  parents_total: number;
  children_total: number;
  families_total: number;
  active_parents_7d: number;
  active_parents_30d: number;
  active_children_7d: number;
  active_children_30d: number;
  exercises_total: number;
  exercises_7d: number;
  exercises_30d: number;
  recent_logins: RecentLogin[];
}
