/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

export interface AdminUserRow {
  id: string;
  email?: string | null;
  name: string;
  role: string;
  is_active: boolean;
  created_at: string;
  last_login_at?: string | null;
  login_count?: number;
  last_exercise_at?: string | null;
  exercises_count?: number;
}
