/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AnnouncementSendResultCounts } from "./announcementSendResultCounts";

/**
 * Bilan d'un envoi (ou d'une simulation).
 */
export interface AnnouncementSendResult {
  dry_run: boolean;
  status: string;
  counts: AnnouncementSendResultCounts;
}
