/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AnnouncementSummaryDeliveryCounts } from "./announcementSummaryDeliveryCounts";

/**
 * Ligne de liste : de quoi savoir où en est chaque annonce.
 */
export interface AnnouncementSummary {
  id: string;
  subject: string;
  from_email: string;
  status: string;
  created_at: string;
  sent_at?: string | null;
  delivery_counts?: AnnouncementSummaryDeliveryCounts;
}
