/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Rédaction d'un brouillon d'annonce.
 */
export interface AnnouncementCreate {
  /**
   * @minLength 1
   * @maxLength 200
   */
  subject: string;
  /** @minLength 1 */
  body_markdown: string;
}
