/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AnnouncementDeliveryItem } from "./announcementDeliveryItem";
import type { AnnouncementDetailDeliveryCounts } from "./announcementDetailDeliveryCounts";

/**
 * Annonce complète, avec son corps et son journal de livraison.
 */
export interface AnnouncementDetail {
  id: string;
  subject: string;
  from_email: string;
  status: string;
  created_at: string;
  sent_at?: string | null;
  delivery_counts?: AnnouncementDetailDeliveryCounts;
  body_markdown: string;
  deliveries?: AnnouncementDeliveryItem[];
}
