/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Aperçu avant envoi : ce que verra un parent, et combien en recevront un.
 */
export interface AnnouncementPreview {
  subject: string;
  html: string;
  text: string;
  recipient_count: number;
}
