/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * État d'envoi vers un destinataire.
 */
export interface AnnouncementDeliveryItem {
  email: string;
  status: string;
  attempts: number;
  error?: string | null;
  sent_at?: string | null;
}
