/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AuditRowDetail } from "./auditRowDetail";

/**
 * Ligne du journal d'audit d'un pack.
 */
export interface AuditRow {
  action: string;
  actor_id?: string | null;
  detail?: AuditRowDetail;
  created_at?: string | null;
}
