/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * État de l'interrupteur d'auto-activation, par enfant.
 */
export interface AutoEnableState {
  child_id: string;
  enabled: boolean;
}
