/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Attribution (ou retrait) de points par un parent.
 */
export interface AwardCreate {
  /** points | behavior */
  wallet: string;
  /** Montant (négatif autorisé pour behavior) */
  amount: number;
  /** Motif (dictée, bonne action…) */
  reason?: string | null;
}
