/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Une ligne d'attribution de points.
 */
export interface AwardResponse {
  id: string;
  wallet: string;
  amount: number;
  reason?: string | null;
  created_at: string;
  acknowledged_at?: string | null;
}
