/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

export interface BodyUploadMyAvatarApiV1AuthMeAvatarPost {
  /** Image d'avatar (PNG, JPEG, WebP, GIF) */
  file: Blob;
}
