/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Un objet d'un catalogue (Pokémon, dinosaure, astre…).
 */
export interface CatalogItem {
  id: number;
  name_fr: string;
  price: number;
  image_url: string;
  /** Anecdote / description (contenu éducatif) */
  fact?: string | null;
}
