/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Résumé d'un catalogue pour le hub des collections.
 */
export interface CatalogInfo {
  slug: string;
  name: string;
  icon: string;
  total: number;
  unlocked: number;
}
