/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Métadonnées d'un catalogue (liste complète, non filtrée) — gestion parent.
 */
export interface CatalogMeta {
  slug: string;
  name: string;
  icon: string;
  total: number;
}
