/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";

/**
 * Schéma pour la création d'un profil enfant
 */
export interface ChildCreate {
  /**
   * Nom de l'enfant
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** Date de naissance */
  birth_date?: string | null;
  /** Niveau scolaire (PS à CM2) */
  level?: LevelEnum | null;
}
