/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la réponse avec les informations d'un enfant
 */
export interface ChildResponse {
  id: string;
  name: string;
  birth_date: string;
  parent_id: string;
  created_at: string;
}
