/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";

/**
 * Schéma pour la réponse avec les informations d'un enfant
 */
export interface ChildResponse {
  id: string;
  name: string;
  birth_date?: string | null;
  parent_id: string;
  level?: LevelEnum | null;
  avatar_url?: string | null;
  created_at: string;
  disabled_collections?: string[];
  role?: string;
  is_owner?: boolean;
}
