/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la création d'un profil enfant
 */
export interface ChildCreate {
  /**
   * Nom de l'enfant
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** Date de naissance */
  birth_date: string;
  /** Email de l'enfant (pour créer le compte) */
  email: string;
  /**
   * Mot de passe (minimum 8 caractères)
   * @minLength 8
   */
  password: string;
}
