/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";

/**
 * Schéma pour la mise à jour d'un profil enfant.

Tous les champs sont optionnels ; seuls ceux fournis sont modifiés.
 */
export interface ChildUpdate {
  /** Nom de l'enfant */
  name?: string | null;
  /** Date de naissance */
  birth_date?: string | null;
  /** Nouveau mot de passe */
  password?: string | null;
  /** Niveau scolaire (PS à CM2) */
  level?: LevelEnum | null;
}
