/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AccessEntry } from "./accessEntry";

/**
 * État d'accès complet d'un enfant : l'interrupteur global et les lignes.

Les packs ``official`` sont absents volontairement : ils sont activés
implicitement au niveau de l'enfant et n'ont jamais de ligne d'accès.
 */
export interface ChildAccessState {
  child_id: string;
  auto_enable_approved_packs: boolean;
  entries?: AccessEntry[];
}
