/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { DailyActivity } from "./dailyActivity";
import type { ErrorLogItem } from "./errorLogItem";
import type { LessonHistoryItem } from "./lessonHistoryItem";
import type { SubjectAccuracy } from "./subjectAccuracy";

/**
 * Historique de progression d'un enfant (parent-facing).
 */
export interface ChildHistoryResponse {
  daily: DailyActivity[];
  lessons: LessonHistoryItem[];
  errors: ErrorLogItem[];
  by_subject: SubjectAccuracy[];
}
