/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { UserAchievementResponse } from "./userAchievementResponse";

/**
 * Statistiques de gamification d'un enfant (tableau de bord parent/enfant).
 */
export interface ChildStatsResponse {
  child_id: string;
  total_xp: number;
  level: number;
  current_level_xp: number;
  next_level_xp: number;
  current_streak: number;
  longest_streak: number;
  total_exercises_completed: number;
  achievements?: UserAchievementResponse[];
}
