/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PokedexEntry } from "./pokedexEntry";

/**
 * État du porte-monnaie XP et de la collection de l'utilisateur.
 */
export interface CollectionSummary {
  /** XP total gagné (inchangé, pilote les niveaux) */
  total_earned: number;
  /** XP dépensé en Pokémon */
  spent: number;
  /** XP dépensable = gagné − dépensé */
  balance: number;
  /** Nombre total de Pokémon du catalogue */
  total_count: number;
  /** Nombre de Pokémon débloqués */
  unlocked_count: number;
  /** Pokémon débloqués (données complètes) */
  collection?: PokedexEntry[];
}
