/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cycle de vie communautaire d'un pack.

La visibilité *familiale* (les enfants de l'auteur) est **indépendante** de ce
statut, à l'exception de ``BLOCKED`` :

- ``DRAFT`` : en cours de rédaction, visible du seul auteur.
- ``PENDING`` : soumis à la modération, déjà utilisable par la famille.
- ``APPROVED`` : listé au catalogue parent ; verrouillé et difficulté ratifiée.
- ``REJECTED`` : refusé pour la communauté ; la famille de l'auteur le garde.
- ``BLOCKED`` : masqué pour tout le monde, auteur inclus (contenu nuisible).
  Reste un simple changement d'état : aucune ligne de progression n'est perdue.
 */
export type CommunityStatus =
  (typeof CommunityStatus)[keyof typeof CommunityStatus];

export const CommunityStatus = {
  draft: "draft",
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  blocked: "blocked",
} as const;
