/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ContinuerCardReason } from "./continuerCardReason";
import type { PackPathLesson } from "./packPathLesson";

/**
 * La leçon recommandée, résolue côté serveur.

Une seule, pour que toutes les surfaces (les deux lentilles, et tout écran
futur) désignent la même action suivante. ``reason`` distingue la reprise
d'un pack entamé du démarrage du pack le moins avancé, ce qui suffit au
client pour choisir son libellé (« Continuer » vs « Commencer »).
 */
export interface ContinuerCard {
  pack_id: string;
  pack_title: string;
  pack_emoji?: string | null;
  reason: ContinuerCardReason;
  lesson: PackPathLesson;
}
