/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contributeur vu côté modération : reconnaissance, conditions, confiance.
 */
export interface ContributorRow {
  user_id: string;
  handle: string;
  terms_version?: string | null;
  terms_accepted_at?: string | null;
  trusted?: boolean;
  trusted_at?: string | null;
  approved_packs?: number;
  pending_packs?: number;
  families_reached?: number;
  trust_threshold: number;
  trust_eligible?: boolean;
}
