/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Conditions de contribution en vigueur et état d'acceptation du compte.
 */
export interface ContributorTerms {
  version: string;
  text: string;
  accepted?: boolean;
  handle?: string | null;
  trusted?: boolean;
}
