/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Statistiques d'un auteur. La reconnaissance est la seule récompense
offerte aux contributeurs : ces nombres doivent donc être réels.
 */
export interface ContributorStats {
  handle?: string | null;
  trusted?: boolean;
  packs_approved?: number;
  packs_pending?: number;
  times_enabled?: number;
  families_reached?: number;
}
