/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Acceptation explicite des conditions, avec le pseudonyme public choisi.

Le pseudonyme est obligatoire ici : c'est la seule identité publiée d'un
contributeur, et la faire choisir au moment de l'acceptation évite qu'un
pseudonyme généré (``Parent-a1b2c3``) devienne son nom public par défaut.
 */
export interface ContributorTermsAccept {
  /**
   * Pseudonyme public
   * @minLength 3
   * @maxLength 24
   */
  handle: string;
}
