/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour l'objectif quotidien
 */
export interface DailyGoalResponse {
  id: string;
  date: string;
  /**
   * XP à gagner aujourd'hui
   * @exclusiveMinimum 0
   */
  xp_target: number;
  /**
   * XP gagné aujourd'hui
   * @minimum 0
   */
  xp_earned: number;
  /**
   * Leçons à compléter aujourd'hui
   * @exclusiveMinimum 0
   */
  lessons_target: number;
  /**
   * Leçons complétées aujourd'hui
   * @minimum 0
   */
  lessons_completed: number;
  /** Objectif complété */
  is_completed: boolean;
  /**
   * Pourcentage de progression
   * @minimum 0
   * @maximum 100
   */
  progress_percentage: number;
}
