/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour créer/mettre à jour un objectif quotidien
 */
export interface DailyGoalCreate {
  /**
   * XP à gagner (1-500)
   * @maximum 500
   * @exclusiveMinimum 0
   */
  xp_target: number;
  /**
   * Leçons à compléter (1-20)
   * @maximum 20
   * @exclusiveMinimum 0
   */
  lessons_target: number;
}
