/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Connexion de développement/tests (montée uniquement si DEBUG).
 */
export interface DevLoginRequest {
  /** Email du parent (créé si absent) */
  email: string;
  /** Nom d'affichage à la création */
  display_name?: string | null;
}
