/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Niveaux de difficulté
 */
export type DifficultyEnum =
  (typeof DifficultyEnum)[keyof typeof DifficultyEnum];

export const DifficultyEnum = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;
