/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Carte « Découvrir » : le strict minimum visible par un enfant.

Ces métadonnées sont visibles **avant** activation — c'est assumé, et c'est
pourquoi la revue de modération porte aussi sur le titre, l'emoji et la
description, pas seulement sur les exercices.
 */
export interface DiscoverPack {
  id: string;
  title: string;
  emoji?: string | null;
  description?: string | null;
  subject_icons?: string[];
  lesson_count?: number;
  families_count?: number;
  author_handle?: string | null;
  requested?: boolean;
}
