/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Un exercice raté (journal des erreurs).
 */
export interface ErrorLogItem {
  exercise_id: string;
  question: string;
  lesson_name: string;
  subject_name: string;
  timestamp: string;
}
