/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResultResponse } from "./exerciseResultResponse";
import type { UnlockedAchievement } from "./unlockedAchievement";

/**
 * Réponse enrichie d'une soumission d'exercice.

Regroupe la correction *et* le résumé de progression (XP, série, complétion
de la leçon, achievements) pour que le frontend affiche le feedback en un
seul appel.
 */
export interface ExerciseSubmitResponse {
  result: ExerciseResultResponse;
  is_correct: boolean;
  xp_awarded?: number;
  total_xp?: number;
  current_streak?: number;
  lesson_completed?: boolean;
  lesson_score?: number | null;
  lesson_stars?: number | null;
  new_achievements?: UnlockedAchievement[];
}
