/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseResultResponseAnswer } from "./exerciseResultResponseAnswer";

/**
 * Schéma de réponse pour le résultat d'un exercice.
 */
export interface ExerciseResultResponse {
  id: string;
  exercise_id: string;
  user_id: string;
  answer: ExerciseResultResponseAnswer;
  is_correct: boolean;
  time_taken: number | null;
  hints_used: number;
  timestamp: string;
}
