/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseSubmitAnswer } from "./exerciseSubmitAnswer";

/**
 * Schéma pour soumettre une réponse d'exercice.
 */
export interface ExerciseSubmit {
  /** Réponse de l'utilisateur */
  answer: ExerciseSubmitAnswer;
  /** Temps pris en secondes */
  time_taken?: number | null;
  /**
   * Nombre d'indices utilisés
   * @minimum 0
   */
  hints_used?: number;
}
