/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { DifficultyEnum } from "./difficultyEnum";
import type { ExerciseCreateContent } from "./exerciseCreateContent";
import type { ExerciseCreateCorrectAnswer } from "./exerciseCreateCorrectAnswer";
import type { ExerciseCreateHintsItem } from "./exerciseCreateHintsItem";
import type { ExerciseCreateMediaUrls } from "./exerciseCreateMediaUrls";
import type { ExerciseType } from "./exerciseType";

/**
 * Schéma pour la création d'un exercice.
 */
export interface ExerciseCreate {
  /** Type d'exercice (jeu canonique) */
  type: ExerciseType;
  /**
   * Question de l'exercice
   * @minLength 1
   */
  question: string;
  /** Contenu de l'exercice (forme dépend du type) */
  content: ExerciseCreateContent;
  /** Réponse correcte (vide pour reveal/pythagore) */
  correct_answer?: ExerciseCreateCorrectAnswer;
  /** Indices progressifs */
  hints?: ExerciseCreateHintsItem[];
  /** Explication de la réponse */
  explanation?: string | null;
  /**
   * Ordre dans la leçon
   * @minimum 0
   */
  order_index?: number;
  /** Niveau de difficulté */
  difficulty?: DifficultyEnum;
  /** URLs des médias associés */
  media_urls?: ExerciseCreateMediaUrls;
  /** ID de la leçon */
  lesson_id: string;
}
