/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { DifficultyEnum } from "./difficultyEnum";
import type { ExerciseType } from "./exerciseType";
import type { ExerciseUpdateContent } from "./exerciseUpdateContent";
import type { ExerciseUpdateCorrectAnswer } from "./exerciseUpdateCorrectAnswer";
import type { ExerciseUpdateHints } from "./exerciseUpdateHints";
import type { ExerciseUpdateMediaUrls } from "./exerciseUpdateMediaUrls";

/**
 * Schéma pour la mise à jour d'un exercice.

Si ``type`` est fourni, ``content`` et ``correct_answer`` doivent l'être
aussi afin de revalider la cohérence de la forme.
 */
export interface ExerciseUpdate {
  /** ID de la leçon */
  lesson_id?: string | null;
  /** Type d'exercice */
  type?: ExerciseType | null;
  /** Question de l'exercice */
  question?: string | null;
  /** Contenu de l'exercice */
  content?: ExerciseUpdateContent;
  /** Réponse correcte */
  correct_answer?: ExerciseUpdateCorrectAnswer;
  /** Indices progressifs */
  hints?: ExerciseUpdateHints;
  /** Explication de la réponse */
  explanation?: string | null;
  /** Ordre dans la leçon */
  order_index?: number | null;
  /** Niveau de difficulté */
  difficulty?: DifficultyEnum | null;
  /** URLs des médias associés */
  media_urls?: ExerciseUpdateMediaUrls;
}
