/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { DifficultyEnum } from "./difficultyEnum";
import type { ExerciseResponseContent } from "./exerciseResponseContent";
import type { ExerciseResponseCorrectAnswer } from "./exerciseResponseCorrectAnswer";
import type { ExerciseResponseHintsItem } from "./exerciseResponseHintsItem";
import type { ExerciseResponseMediaUrls } from "./exerciseResponseMediaUrls";
import type { ExerciseType } from "./exerciseType";

/**
 * Schéma de réponse pour un exercice.
 */
export interface ExerciseResponse {
  /** Type d'exercice (jeu canonique) */
  type: ExerciseType;
  /**
   * Question de l'exercice
   * @minLength 1
   */
  question: string;
  /** Contenu de l'exercice (forme dépend du type) */
  content: ExerciseResponseContent;
  /** Réponse correcte (vide pour reveal/pythagore) */
  correct_answer?: ExerciseResponseCorrectAnswer;
  /** Indices progressifs */
  hints?: ExerciseResponseHintsItem[];
  /** Explication de la réponse */
  explanation?: string | null;
  /**
   * Ordre dans la leçon
   * @minimum 0
   */
  order_index?: number;
  /** Niveau de difficulté */
  difficulty?: DifficultyEnum;
  /** URLs des médias associés */
  media_urls?: ExerciseResponseMediaUrls;
  id: string;
  lesson_id: string;
}
