/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contenu de l'exercice (forme dépend du type)
 */
export type ExerciseResponseContent = { [key: string]: unknown };
