/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Types d'exercices supportés (jeu de types canonique).

Volontairement restreint aux 4 types réellement implémentés et alimentés
en contenu, en cohérence avec le frontend :
- MULTIPLE_CHOICE : QCM (réponse unique ou multiple)
- FILL_BLANKS : compléter les trous (marqueurs ``___`` dans le texte)
- REVEAL : carte à révéler (blague) — pas de bonne réponse, étoile garantie
- PYTHAGORE : mini-jeu de table de multiplication (grille)
 */
export type ExerciseType = (typeof ExerciseType)[keyof typeof ExerciseType];

export const ExerciseType = {
  multiple_choice: "multiple_choice",
  fill_blanks: "fill_blanks",
  reveal: "reveal",
  pythagore: "pythagore",
} as const;
