/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseEditContent } from "./exerciseEditContent";
import type { ExerciseEditCorrectAnswer } from "./exerciseEditCorrectAnswer";

/**
 * Retouche rapide d'un exercice existant. Les champs absents sont conservés.
 */
export interface ExerciseEdit {
  id: string;
  question?: string | null;
  content?: ExerciseEditContent;
  correct_answer?: ExerciseEditCorrectAnswer;
  difficulty_level?: number | null;
  /** Position dans la leçon */
  order_index?: number | null;
}
