/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";

export type GetCatalogueApiV1LibraryCatalogueGetParams = {
  /**
   * Ne garder que les packs couvrant ce niveau
   */
  level?: LevelEnum | null;
  /**
   * Slug de matière
   */
  subject?: string | null;
  /**
   * Étiquette de thème
   */
  tag?: string | null;
  /**
   * @pattern ^(newest|most_enabled)$
   */
  sort?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * @minimum 0
   */
  offset?: number;
};
