/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatus } from "./communityStatus";

export type GetQueueApiV1ModerationQueueGetParams = {
  status?: CommunityStatus;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
