/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ReportStatus } from "./reportStatus";

export type GetReportsApiV1ModerationReportsGetParams = {
  status?: ReportStatus | null;
  /**
   * @minimum 1
   * @maximum 200
   */
  limit?: number;
};
