/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Connexion via Google Identity Services (flux id_token).
 */
export interface GoogleAuthRequest {
  /** ID token (JWT) renvoyé par Google Identity Services */
  credential: string;
}
