/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Un responsable d'un enfant (pour l'écran de gestion des accès).
 */
export interface GuardianResponse {
  guardian_id: string;
  name: string;
  avatar_url?: string | null;
  role: string;
  is_self: boolean;
}
