/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Aperçu public d'une invitation (page d'acceptation, avant connexion).
 */
export interface InvitationPreview {
  valid: boolean;
  kind?: string | null;
  inviter_name?: string | null;
  child_name?: string | null;
  child_avatar?: string | null;
  children_names?: string[];
}
