/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Invitation créée : le jeton sert à construire le lien à partager.
 */
export interface InvitationResponse {
  token: string;
  kind: string;
  child_id?: string | null;
  expires_at: string;
}
