/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Création d'une invitation.

- ``kind='child'`` : partage d'un enfant précis (``child_id`` requis).
- ``kind='all'`` : invitation d'un co-parent (tous les enfants + futurs).
 */
export interface InvitationCreate {
  /** 'child' ou 'all' */
  kind: string;
  /** Enfant partagé (kind='child') */
  child_id?: string | null;
  /** Rôle accordé (kind='child') */
  role?: string;
}
