/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour une entrée du classement familial
 */
export interface LeaderboardEntry {
  user_id: string;
  display_name: string;
  avatar_url?: string | null;
  /**
   * XP total
   * @minimum 0
   */
  total_xp: number;
  /**
   * Niveau
   * @minimum 1
   */
  level: number;
  /**
   * Série actuelle
   * @minimum 0
   */
  current_streak: number;
  /**
   * Leçons complétées
   * @minimum 0
   */
  lessons_completed: number;
  /**
   * Position dans le classement
   * @minimum 1
   */
  rank: number;
}
