/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LessonResponseUnlockCriteria } from "./lessonResponseUnlockCriteria";

/**
 * Schéma de réponse pour une leçon
 */
export interface LessonResponse {
  /**
   * Nom de la leçon
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Description de la leçon */
  description?: string | null;
  /**
   * Ordre dans le parcours
   * @minimum 0
   */
  order_index?: number;
  /** Critères de déverrouillage */
  unlock_criteria?: LessonResponseUnlockCriteria;
  /**
   * Récompense XP
   * @minimum 0
   */
  xp_reward?: number;
  /** Durée estimée en minutes */
  estimated_duration?: number | null;
  /** URL de l'image de couverture */
  cover_image?: string | null;
  /** Leçon publiée ou non */
  is_published?: boolean;
  id: string;
  path_id: string;
  /** ID de la matière (via le parcours) */
  subject_id?: string | null;
  /** Verrouillée pour l'enfant tant que le palier inférieur n'est pas terminé */
  locked?: boolean;
}
