/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ExerciseEdit } from "./exerciseEdit";

/**
 * Retouche rapide d'une leçon existante et de ses exercices.
 */
export interface LessonEdit {
  id: string;
  name?: string | null;
  description?: string | null;
  /** Palier (1 Découverte, 2 Entraînement, 3 Défi) */
  tier?: number | null;
  exercises?: ExerciseEdit[];
}
