/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Une leçon dans l'historique (terminée ou en cours).
 */
export interface LessonHistoryItem {
  lesson_id: string;
  lesson_name: string;
  subject_name: string;
  subject_icon?: string | null;
  status: string;
  score?: number | null;
  stars?: number | null;
  attempts?: number;
  completed_at?: string | null;
}
