/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LessonUpdateUnlockCriteria } from "./lessonUpdateUnlockCriteria";

/**
 * Schéma pour la mise à jour d'une leçon
 */
export interface LessonUpdate {
  /** ID du parcours d'apprentissage */
  path_id?: string | null;
  /** Nom de la leçon */
  name?: string | null;
  /** Description de la leçon */
  description?: string | null;
  /** Ordre dans le parcours */
  order_index?: number | null;
  /** Critères de déverrouillage */
  unlock_criteria?: LessonUpdateUnlockCriteria;
  /** Récompense XP */
  xp_reward?: number | null;
  /** Durée estimée en minutes */
  estimated_duration?: number | null;
  /** URL de l'image de couverture */
  cover_image?: string | null;
  /** Leçon publiée ou non */
  is_published?: boolean | null;
}
