/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Critères de déverrouillage
 */
export type LessonUpdateUnlockCriteria = { [key: string]: unknown } | null;
