/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ProgressStatus } from "./progressStatus";

/**
 * Schéma pour la progression d'une leçon
 */
export interface LessonProgressResponse {
  id: string;
  lesson_id: string;
  lesson_name?: string | null;
  status: ProgressStatus;
  /**
   * Score en pourcentage (0-100)
   * @minimum 0
   * @maximum 100
   */
  score: number;
  /**
   * Étoiles obtenues (0-3)
   * @minimum 0
   * @maximum 3
   */
  stars: number;
  /**
   * Nombre de tentatives
   * @minimum 0
   */
  attempts: number;
  /**
   * Temps passé en secondes
   * @minimum 0
   */
  time_spent: number;
  started_at?: string | null;
  completed_at?: string | null;
}
