/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LessonCreateUnlockCriteria } from "./lessonCreateUnlockCriteria";

/**
 * Schéma pour la création d'une leçon
 */
export interface LessonCreate {
  /**
   * Nom de la leçon
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Description de la leçon */
  description?: string | null;
  /**
   * Ordre dans le parcours
   * @minimum 0
   */
  order_index?: number;
  /** Critères de déverrouillage */
  unlock_criteria?: LessonCreateUnlockCriteria;
  /**
   * Récompense XP
   * @minimum 0
   */
  xp_reward?: number;
  /** Durée estimée en minutes */
  estimated_duration?: number | null;
  /** URL de l'image de couverture */
  cover_image?: string | null;
  /** Leçon publiée ou non */
  is_published?: boolean;
  /** ID du parcours d'apprentissage */
  path_id: string;
}
