/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

export type ListExercisesApiV1ExercisesGetParams = {
  /**
   * Nombre d'éléments à ignorer
   * @minimum 0
   */
  skip?: number;
  /**
   * Nombre maximum d'éléments à retourner
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Filtrer par leçon
   */
  lesson_id?: string | null;
};
