/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatus } from "./communityStatus";
import type { LevelEnum } from "./levelEnum";
import type { PackOrigin } from "./packOrigin";
import type { ValidationIssue } from "./validationIssue";

/**
 * Une ligne de file : de quoi trier et prioriser sans ouvrir le pack.
 */
export interface ModerationQueueEntry {
  id: string;
  title: string;
  emoji?: string | null;
  description?: string | null;
  origin: PackOrigin;
  community_status: CommunityStatus;
  author_handle?: string | null;
  tags?: string[];
  quality_score?: number | null;
  difficulty_ratified?: boolean;
  locked?: boolean;
  level_min: LevelEnum;
  level_max: LevelEnum;
  lesson_count?: number;
  exercise_count?: number;
  subject_icons?: string[];
  families_count?: number;
  created_at?: string | null;
  submitted_at?: string | null;
  author_id?: string | null;
  warnings?: ValidationIssue[];
  open_reports?: number;
  cloned_from_pack_id?: string | null;
  cloned_from_title?: string | null;
  reviewed_at?: string | null;
  review_notes?: string | null;
}
