/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatus } from "./communityStatus";
import type { ModerationQueueEntry } from "./moderationQueueEntry";

/**
 * File d'attente d'un statut donné.
 */
export interface ModerationQueue {
  status: CommunityStatus;
  count: number;
  items?: ModerationQueueEntry[];
}
