/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { SudokuDifficulty } from "./sudokuDifficulty";

/**
 * Demande d'une nouvelle grille pour un niveau donné.
 */
export interface NewPuzzleRequest {
  difficulty?: SudokuDifficulty;
}
