/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Verdict d'un responsable sur une demande, derrière le code PIN parent.

Le PIN voyage dans le corps (et non en en-tête) pour rester identique à
``POST /auth/verify-pin`` : un seul geste côté enfant-qui-passe-le-téléphone.
 */
export interface PackRequestDecision {
  approve: boolean;
  /** Code PIN parent à 4 chiffres */
  pin: string;
}
