/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ContinuerCard } from "./continuerCard";
import type { PackPathEntry } from "./packPathEntry";
import type { PackPathResponseLens } from "./packPathResponseLens";

/**
 * Chemin complet : lentille active, packs, et carte « Continuer ».

``continuer`` à ``None`` n'est pas une erreur : c'est l'état vide honnête
(tout est terminé, ou aucun pack n'est activé pour cet enfant).
 */
export interface PackPathResponse {
  lens?: PackPathResponseLens;
  entries?: PackPathEntry[];
  continuer?: ContinuerCard | null;
}
