/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * « Je veux ça ! » — une demande, jamais un accès.
 */
export interface PackRequestCreate {
  pack_id: string;
}
