/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PackExercisePreviewContent } from "./packExercisePreviewContent";
import type { PackExercisePreviewCorrectAnswer } from "./packExercisePreviewCorrectAnswer";

/**
 * Un exercice tel qu'il sera présenté à l'enfant (aperçu et revue).
 */
export interface PackExercisePreview {
  id?: string | null;
  order_index: number;
  type: string;
  question: string;
  content?: PackExercisePreviewContent;
  correct_answer?: PackExercisePreviewCorrectAnswer;
  explanation?: string | null;
  difficulty_level?: number | null;
}
