/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatus } from "./communityStatus";
import type { PackEditChanges } from "./packEditChanges";

/**
 * Décision et/ou correction sur un pack.

``verdict`` omis signifie « correction seule » : aucun statut n'est écrit.
C'est l'invariant du dispositif — l'analyse peut être automatisée, la
décision non ; un verdict que l'admin n'a pas prononcé ne doit jamais
apparaître en base.
 */
export interface PackReviewRequest {
  verdict?: CommunityStatus | null;
  notes?: string | null;
  quality_score?: number | null;
  ratify_difficulty?: boolean | null;
  changes?: PackEditChanges | null;
}
