/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LessonEdit } from "./lessonEdit";

/**
 * Corrections apportées depuis l'écran d'aperçu, revalidées avant écriture.
 */
export interface PackQuickEdit {
  title?: string | null;
  emoji?: string | null;
  description?: string | null;
  tags?: string[] | null;
  lessons?: LessonEdit[];
}
