/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";

/**
 * Corrections admin. Seuls les champs *fournis* sont écrits.

Le titre, l'emoji et la description sont éditables parce qu'ils sont
visibles par l'enfant avant toute activation.
 */
export interface PackEditChanges {
  title?: string | null;
  emoji?: string | null;
  description?: string | null;
  tags?: string[] | null;
  level_min?: LevelEnum | null;
  level_max?: LevelEnum | null;
}
