/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Cumul de progression d'un pack : ce que la ligne trophée doit pouvoir dire.

``stars_earned``, ``xp_banked`` et ``completed_at`` sont obligatoires dans la
charge utile : un pack replié sans eux se lirait comme du contenu *retiré* à
l'enfant, alors qu'il s'agit de contenu *capitalisé* (décision 17).
 */
export interface PackPathRollup {
  lessons_total?: number;
  lessons_completed?: number;
  stars_earned?: number;
  stars_total?: number;
  xp_banked?: number;
  xp_total?: number;
  completed_at?: string | null;
  complete?: boolean;
}
