/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PackLensUpdateLens } from "./packLensUpdateLens";

/**
 * Bascule de lentille, persistée par enfant (``Profile.pack_lens``).
 */
export interface PackLensUpdate {
  lens: PackLensUpdateLens;
}
