/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Provenance d'un pack.

``OFFICIAL`` : rédigé par l'équipe Explorito ; activé implicitement pour tous
les enfants du niveau (c'est ainsi que le contenu historique est repris).
``COMMUNITY`` : rédigé par un parent ; n'atteint un enfant que via une ligne
d'accès explicite.
 */
export type PackOrigin = (typeof PackOrigin)[keyof typeof PackOrigin];

export const PackOrigin = {
  official: "official",
  community: "community",
} as const;
