/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";
import type { PackExercisePreview } from "./packExercisePreview";

/**
 * Une leçon du pack, avec sa matière, son niveau et son palier.
 */
export interface PackLessonPreview {
  id?: string | null;
  name: string;
  description?: string | null;
  subject_slug: string;
  subject_name?: string | null;
  subject_icon?: string | null;
  level: LevelEnum;
  tier: number;
  xp_reward?: number;
  exercises?: PackExercisePreview[];
}
