/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

export type PackPathResponseLens =
  (typeof PackPathResponseLens)[keyof typeof PackPathResponseLens];

export const PackPathResponseLens = {
  themes: "themes",
  matieres: "matieres",
} as const;
