/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PackPathLesson } from "./packPathLesson";
import type { PackPathRollup } from "./packPathRollup";
import type { PackSummary } from "./packSummary";

/**
 * Un pack du chemin : sa carte, ses leçons ordonnées par palier, son cumul.
 */
export interface PackPathEntry {
  pack: PackSummary;
  lessons?: PackPathLesson[];
  rollup: PackPathRollup;
}
