/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatus } from "./communityStatus";
import type { LevelEnum } from "./levelEnum";
import type { PackLessonPreview } from "./packLessonPreview";
import type { PackOrigin } from "./packOrigin";
import type { ValidationIssue } from "./validationIssue";

/**
 * Pack complet : le contenu que l'adulte doit pouvoir lire avant d'activer.
 */
export interface PackDetail {
  id: string;
  title: string;
  emoji?: string | null;
  description?: string | null;
  origin: PackOrigin;
  community_status: CommunityStatus;
  author_handle?: string | null;
  tags?: string[];
  quality_score?: number | null;
  difficulty_ratified?: boolean;
  locked?: boolean;
  level_min: LevelEnum;
  level_max: LevelEnum;
  lesson_count?: number;
  exercise_count?: number;
  subject_icons?: string[];
  families_count?: number;
  created_at?: string | null;
  submitted_at?: string | null;
  lessons?: PackLessonPreview[];
  warnings?: ValidationIssue[];
  cloned_from_pack_id?: string | null;
  review_notes?: string | null;
  reviewed_at?: string | null;
}
