/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Demande d'un enfant, telle que la voient l'enfant et ses responsables.
 */
export interface PackRequestResponse {
  id: string;
  child_id: string;
  child_name?: string | null;
  pack_id: string;
  pack_title: string;
  pack_emoji?: string | null;
  status: string;
  created_at?: string | null;
  decided_at?: string | null;
  decided_by?: string | null;
}
