/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LevelEnum } from "./levelEnum";
import type { ProgressStatus } from "./progressStatus";

/**
 * Une leçon telle qu'elle apparaît sur le chemin, verrou et progression compris.

Les noms de champs communs sont alignés sur
:class:`app.schemas.pack.PackLessonPreview` pour que le frontend manipule la
même forme de leçon partout. Ce n'est volontairement **pas** une sous-classe :
l'aperçu embarque ``exercises``, or le chemin d'accueil liste des dizaines de
leçons et n'en affiche aucun exercice — hériter multiplierait la charge utile
de l'écran le plus consulté de l'application.
 */
export interface PackPathLesson {
  id: string;
  name: string;
  description?: string | null;
  subject_id: string;
  subject_slug: string;
  subject_name?: string | null;
  subject_icon?: string | null;
  level: LevelEnum;
  tier: number;
  xp_reward?: number;
  exercise_count?: number;
  locked?: boolean;
  status?: ProgressStatus;
  stars?: number;
  score?: number;
  attempts?: number;
  started_at?: string | null;
  completed_at?: string | null;
  xp_earned?: number;
}
