/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Jeton d'envoi remis à l'assistant, plus ce qu'il doit savoir du compte.
 */
export interface PairingResult {
  /** Secret en clair — à stocker localement, non récupérable ensuite */
  token: string;
  prefix: string;
  handle?: string | null;
  terms_accepted?: boolean;
  terms_version: string;
  /** URL publique de l'application, à mémoriser avec le jeton */
  app_url: string;
}
