/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Code court à dicter à son assistant, en échange d'un jeton d'envoi.
 */
export interface PairingCode {
  /** Code à usage unique, à lire à voix haute */
  code: string;
  expires_at: string;
  expires_in_seconds: number;
}
