/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Code présenté par un assistant pour se configurer.
 */
export interface PairingClaim {
  /**
   * @minLength 4
   * @maxLength 32
   */
  code: string;
}
