/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Définition ou vérification d'un code PIN parent (4 chiffres).
 */
export interface PinRequest {
  /** Code PIN à 4 chiffres */
  pin: string;
}
