/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Entrée du catalogue enrichie de l'état de possession (pour la grille).
 */
export interface PokedexGridEntry {
  id: number;
  name_fr: string;
  price: number;
  image_url: string;
  owned?: boolean;
}
