/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Une entrée du catalogue Pokémon.
 */
export interface PokedexEntry {
  id: number;
  name_fr: string;
  price: number;
  image_url: string;
}
