/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Acceptation explicite d'une version précise.

La version est envoyée par le client et vérifiée côté serveur : accepter
« la version en vigueur » sans la nommer laisserait passer une acceptation
portant sur un texte que le parent n'avait pas sous les yeux.
 */
export interface PrivacyAccept {
  /** Version affichée au parent au moment de la case cochée */
  version: string;
}
