/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Politique en vigueur, et son acceptation par le compte qui la demande.
 */
export interface PrivacyPolicy {
  /** Version datée du texte en vigueur */
  version: string;
  /** Texte intégral de la politique */
  text: string;
  /** Vrai si ce compte a accepté la version en vigueur */
  accepted?: boolean;
  /** Horodatage de l'acceptation enregistrée */
  accepted_at?: string | null;
}
