/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour les informations du profil
 */
export interface ProfileResponse {
  id: string;
  display_name: string;
  avatar_url?: string | null;
  date_of_birth?: string | null;
  is_child: boolean;
  created_at: string;
}
