/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Mise à jour de son propre profil (avatar, nom d'affichage).
 */
export interface ProfileUpdate {
  /** Nom d'affichage */
  display_name?: string | null;
  /** Avatar (emoji ou URL d'image) */
  avatar_url?: string | null;
}
