/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { LessonProgressResponse } from "./lessonProgressResponse";
import type { SubjectProgressResponse } from "./subjectProgressResponse";

/**
 * Schéma pour le tableau de bord de progression
 */
export interface ProgressDashboard {
  /**
   * XP total de l'utilisateur
   * @minimum 0
   */
  total_xp: number;
  /**
   * Niveau global de l'utilisateur
   * @minimum 1
   */
  overall_level: number;
  /**
   * Série de jours consécutifs
   * @minimum 0
   */
  current_streak: number;
  /**
   * Leçons complétées aujourd'hui
   * @minimum 0
   */
  lessons_completed_today: number;
  /**
   * Total de leçons complétées
   * @minimum 0
   */
  total_lessons_completed: number;
  /** Progression par matière */
  subjects_progress?: SubjectProgressResponse[];
  /** Leçons récentes */
  recent_lessons?: LessonProgressResponse[];
  /**
   * Nombre d'achievements débloqués
   * @minimum 0
   */
  achievements_count: number;
  /**
   * XP nécessaire pour le prochain niveau
   * @exclusiveMinimum 0
   */
  next_level_xp: number;
}
