/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Statut de progression d'une leçon
 */
export type ProgressStatus =
  (typeof ProgressStatus)[keyof typeof ProgressStatus];

export const ProgressStatus = {
  locked: "locked",
  available: "available",
  started: "started",
  completed: "completed",
} as const;
