/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Requête d'achat d'un objet de collection.
 */
export interface PurchaseRequest {
  /** Slug du catalogue (pokemon, dinosaurs, solar_system) */
  catalog: string;
  /**
   * ID de l'objet à débloquer
   * @minimum 1
   */
  item_id: number;
}
