/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CatalogItem } from "./catalogItem";

/**
 * Résultat d'un achat.
 */
export interface PurchaseResponse {
  item: CatalogItem;
  catalog: string;
  /** Nouveau solde XP après achat */
  balance: number;
  /** Objets débloqués dans ce catalogue */
  unlocked_count: number;
}
