/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PokedexEntry } from "./pokedexEntry";

/**
 * Résultat d'un achat.
 */
export interface PurchaseResponse {
  pokemon: PokedexEntry;
  /** Nouveau solde XP après achat */
  balance: number;
  unlocked_count: number;
}
