/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Requête d'achat d'un Pokémon.
 */
export interface PurchaseRequest {
  /**
   * ID du Pokémon à débloquer
   * @minimum 1
   */
  pokemon_id: number;
}
