/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { SudokuDifficulty } from "./sudokuDifficulty";

/**
 * Grille générée : indices de départ (0 = case vide) et métadonnées.
 */
export interface PuzzleResponse {
  session_id: string;
  difficulty: SudokuDifficulty;
  /** Côté de la grille (4, 6 ou 8) */
  size: number;
  /** Hauteur d'un bloc */
  box_rows: number;
  /** Largeur d'un bloc */
  box_cols: number;
  /** Grille de départ, 0 pour les cases à remplir */
  puzzle: number[][];
  /** XP attribué en cas de résolution */
  xp_reward: number;
}
