/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PythagoreItemResult } from "./pythagoreItemResult";

/**
 * Résultat de la session : score, série, XP attribué (après plafond) et solde.
 */
export interface PythagoreSessionResponse {
  correct: number;
  total: number;
  longest_streak: number;
  xp_earned: number;
  /** Vrai si le plafond quotidien a limité l'XP */
  capped: boolean;
  /** Solde XP dépensable (Pokédex) après la session */
  balance: number;
  results: PythagoreItemResult[];
}
