/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Correction d'une question (réponse attendue vs donnée).
 */
export interface PythagoreItemResult {
  a: number;
  b: number;
  answer: number;
  expected: number;
  correct: boolean;
}
