/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { PythagoreDifficulty } from "./pythagoreDifficulty";
import type { PythagoreItem } from "./pythagoreItem";

/**
 * Session soumise : difficulté choisie + questions répondues (1 à 20).
 */
export interface PythagoreSessionRequest {
  difficulty?: PythagoreDifficulty;
  /**
   * @minItems 1
   * @maxItems 20
   */
  items: PythagoreItem[];
}
