/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Difficulté du défi (détermine les tables proposées et l'XP de base).
 */
export type PythagoreDifficulty =
  (typeof PythagoreDifficulty)[keyof typeof PythagoreDifficulty];

export const PythagoreDifficulty = {
  facile: "facile",
  moyen: "moyen",
  difficile: "difficile",
} as const;
