/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Un événement d'activité : connexion parent ou session d'exercices enfant.
 */
export interface RecentActivity {
  kind: string;
  label: string;
  detail: string;
  at: string;
}
