/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Leçon récente pour le fil « Nouveautés » (avec infos matière).
 */
export interface RecentLessonResponse {
  id: string;
  name: string;
  subject_id: string;
  subject_name: string;
  subject_icon?: string | null;
  subject_color?: string | null;
  created_at: string;
  locked?: boolean;
}
