/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

export type RecentLessonsApiV1LessonsRecentGetParams = {
  /**
   * @minimum 1
   * @maximum 30
   */
  limit?: number;
};
