/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la requête de rafraîchissement du token
 */
export interface RefreshTokenRequest {
  /** Token de rafraîchissement */
  refresh_token: string;
}
