/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ReportStatus } from "./reportStatus";

/**
 * Signalement de parent, tel que listé côté modération.
 */
export interface ReportRow {
  id: string;
  pack_id: string;
  pack_title: string;
  reason: string;
  details?: string | null;
  status: ReportStatus;
  created_at?: string | null;
  resolved_at?: string | null;
}
