/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ReportReason } from "./reportReason";

/**
 * Signalement d'un pack par un parent.
 */
export interface ReportCreate {
  reason: ReportReason;
  details?: string | null;
}
