/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Signalement enregistré (le parent n'a pas accès à la suite du traitement).
 */
export interface ReportResponse {
  id: string;
  pack_id: string;
  reason: string;
  status: string;
  created_at?: string | null;
}
