/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Motif d'un signalement de pack par un parent.

Liste courte et fermée : un champ libre produit des signalements
intriables, et le motif détermine l'urgence du traitement (``PERSONAL_DATA``
et ``INAPPROPRIATE`` peuvent mener à ``blocked``).
 */
export type ReportReason = (typeof ReportReason)[keyof typeof ReportReason];

export const ReportReason = {
  inappropriate: "inappropriate",
  wrong_content: "wrong_content",
  personal_data: "personal_data",
  duplicate: "duplicate",
  other: "other",
} as const;
