/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ReportStatus } from "./reportStatus";

/**
 * Clôture d'un signalement, avec blocage éventuel du pack visé.

``open`` est refusé par le service : rouvrir un signalement traité se fait
en en créant un nouveau, sinon le journal devient illisible.
 */
export interface ReportDecisionRequest {
  status: ReportStatus;
  block_pack?: boolean;
}
