/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour une récompense débloquée
 */
export interface RewardResponse {
  id: string;
  /** Type de récompense: sticker, trophy, avatar, theme */
  type: string;
  name: string;
  image_url?: string | null;
  unlocked_at: string;
}
