/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Un code d'inscription, tel que listé dans la surface admin.
 */
export interface SignupInviteRow {
  token: string;
  expires_at: string;
  created_at: string;
  accepted_at?: string | null;
  accepted_by_email?: string | null;
  revoked_at?: string | null;
  is_usable: boolean;
  url: string;
}
