/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Solution soumise : grille complète size×size (valeurs 1..size).
 */
export interface SolveRequest {
  grid: number[][];
}
