/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Résultat de la vérification serveur.
 */
export interface SolveResponse {
  correct: boolean;
  /** Grille déjà validée auparavant */
  already_solved?: boolean;
  /** XP crédité (0 si déjà résolu ou incorrect) */
  xp_earned?: number;
  /** Solde XP dépensable (Pokédex) après vérification */
  balance?: number;
}
