/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la série de jours consécutifs
 */
export interface StreakResponse {
  /**
   * Série actuelle de jours
   * @minimum 0
   */
  current_streak: number;
  /**
   * Plus longue série de jours
   * @minimum 0
   */
  longest_streak: number;
  last_activity_date?: string | null;
  /**
   * Nombre de jokers utilisés
   * @minimum 0
   */
  freeze_used: number;
}
