/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma de réponse pour une matière
 */
export interface SubjectResponse {
  /**
   * Nom de la matière
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Slug unique pour l'URL
   * @minLength 1
   * @maxLength 100
   */
  slug: string;
  /** Description de la matière */
  description?: string | null;
  /** Emoji ou URL d'icône */
  icon?: string | null;
  /** Code couleur hexadécimal */
  color?: string | null;
  /**
   * Ordre d'affichage
   * @minimum 0
   */
  order_index?: number;
  /** Matière active ou non */
  is_active?: boolean;
  id: string;
  /** Nombre total de leçons dans cette matière */
  lesson_count?: number;
}
