/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Taux de réussite par matière (courbe de progression).
 */
export interface SubjectAccuracy {
  subject_name: string;
  subject_icon?: string | null;
  attempts: number;
  correct: number;
  accuracy: number;
}
