/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la progression d'une matière
 */
export interface SubjectProgressResponse {
  id: string;
  subject_id: string;
  subject_name?: string | null;
  /**
   * XP total gagné dans cette matière
   * @minimum 0
   */
  total_xp: number;
  /**
   * Niveau atteint dans cette matière
   * @minimum 1
   */
  level: number;
  /**
   * Nombre de leçons complétées
   * @minimum 0
   */
  lessons_completed: number;
  /**
   * Taux de réussite en pourcentage
   * @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$
   */
  accuracy_rate: string;
  last_activity?: string | null;
}
