/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Avancement d'une matière pour l'enfant : leçons terminées / total.

Calculé au niveau scolaire de l'enfant (leçons publiées uniquement). Permet
d'afficher une barre de progression par matière (où l'enfant est en retard).
 */
export interface SubjectOverviewItem {
  subject_id: string;
  /**
   * Leçons publiées à son niveau
   * @minimum 0
   */
  total_lessons: number;
  /**
   * Leçons terminées
   * @minimum 0
   */
  completed_lessons: number;
}
