/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la mise à jour d'une matière
 */
export interface SubjectUpdate {
  /** Nom de la matière */
  name?: string | null;
  /** Slug unique pour l'URL */
  slug?: string | null;
  /** Description de la matière */
  description?: string | null;
  /** Emoji ou URL d'icône */
  icon?: string | null;
  /** Code couleur hexadécimal */
  color?: string | null;
  /** Ordre d'affichage */
  order_index?: number | null;
  /** Matière active ou non */
  is_active?: boolean | null;
}
