/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Niveau du défi Sudoku (détermine la taille de grille et l'XP).
 */
export type SudokuDifficulty =
  (typeof SudokuDifficulty)[keyof typeof SudokuDifficulty];

export const SudokuDifficulty = {
  easy: "easy",
  medium: "medium",
  hard: "hard",
} as const;
