/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la réponse avec le token JWT
 */
export interface Token {
  /** Token d'accès JWT */
  access_token: string;
  /** Token de rafraîchissement */
  refresh_token?: string | null;
  /** Type de token */
  token_type?: string;
  /** Durée de validité en secondes */
  expires_in: number;
}
