/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Promotion (ou révocation) explicite du palier de confiance.
 */
export interface TrustRequest {
  trusted: boolean;
}
