/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Achievement nouvellement débloqué renvoyé après une soumission.
 */
export interface UnlockedAchievement {
  id: string;
  name: string;
  icon?: string | null;
}
