/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Désinscription depuis le lien d'un email (jeton signé, sans connexion).
 */
export interface UnsubscribeRequest {
  /** @minLength 1 */
  token: string;
}
