/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Jeton fraîchement émis : seule et unique occasion de lire le secret.
 */
export interface UploadTokenCreated {
  id: string;
  prefix: string;
  label?: string | null;
  created_at?: string | null;
  last_used_at?: string | null;
  revoked_at?: string | null;
  active?: boolean;
  /** Secret en clair — non récupérable ensuite */
  token: string;
}
