/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Jeton d'envoi tel qu'affiché dans le profil (jamais le secret).
 */
export interface UploadTokenResponse {
  id: string;
  prefix: string;
  label?: string | null;
  created_at?: string | null;
  last_used_at?: string | null;
  revoked_at?: string | null;
  active?: boolean;
}
