/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Demande d'émission d'un jeton d'envoi.
 */
export interface UploadTokenCreate {
  /** Étiquette pour reconnaître le jeton */
  label?: string | null;
}
