/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CommunityStatus } from "./communityStatus";
import type { ValidationIssue } from "./validationIssue";

/**
 * Réponse d'un envoi accepté : de quoi ouvrir l'aperçu et lire les constats.
 */
export interface UploadResult {
  pack_id: string;
  preview_url: string;
  community_status: CommunityStatus;
  /**
   * @minimum 0
   * @maximum 100
   */
  quality_score: number;
  warnings?: ValidationIssue[];
  flags?: ValidationIssue[];
}
