/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileResponse } from "./profileResponse";
import type { UserRole } from "./userRole";

/**
 * Schéma pour la réponse avec les informations utilisateur
 */
export interface UserResponse {
  id: string;
  email: string;
  role: UserRole;
  is_active: boolean;
  created_at: string;
  profile?: ProfileResponse | null;
}
