/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from "./userRole";

/**
 * Schéma pour l'inscription d'un nouvel utilisateur
 */
export interface UserRegister {
  /** Adresse email de l'utilisateur */
  email: string;
  /**
   * Mot de passe (minimum 8 caractères)
   * @minLength 8
   */
  password: string;
  /**
   * Nom d'affichage
   * @minLength 2
   * @maxLength 100
   */
  display_name: string;
  /** Rôle de l'utilisateur */
  role?: UserRole;
  /** Date de naissance */
  date_of_birth?: string | null;
  /** Email du parent (pour les enfants) */
  parent_email?: string | null;
}
