/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { AchievementResponse } from "./achievementResponse";

/**
 * Schéma pour un achievement débloqué par l'utilisateur
 */
export interface UserAchievementResponse {
  id: string;
  achievement_id: string;
  achievement: AchievementResponse;
  unlocked_at: string;
}
