/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schéma pour la connexion
 */
export interface UserLogin {
  /** Adresse email */
  email: string;
  /** Mot de passe */
  password: string;
}
