/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationIssueSeverity } from "./validationIssueSeverity";

/**
 * Un constat du validateur, ancré sur la leçon/l'exercice fautif.

``severity`` porte toute la sémantique :

- ``error`` : refus dur (forme, ``difficulty_level`` manquant, plafonds, langue) ;
- ``warning`` : compte dans le score de qualité, ne bloque pas ;
- ``flag`` : annotation à l'attention d'un humain (grossièreté, quasi-doublon),
  qui ne bloque jamais parce que ces détecteurs ont de vrais faux positifs.
 */
export interface ValidationIssue {
  severity: ValidationIssueSeverity;
  code: string;
  message: string;
  lesson_index?: number | null;
  exercise_index?: number | null;
  field?: string | null;
}
