/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */

export type ValidationIssueSeverity =
  (typeof ValidationIssueSeverity)[keyof typeof ValidationIssueSeverity];

export const ValidationIssueSeverity = {
  error: "error",
  warning: "warning",
  flag: "flag",
} as const;
