/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CatalogInfo } from "./catalogInfo";

/**
 * Deux porte-monnaies dépensables + avancement par catalogue.

``total_earned/spent/balance`` = porte-monnaie **Points** (XP + hardskill).
``behavior_*`` = porte-monnaie **Comportement**.
 */
export interface WalletSummary {
  /** Points gagnés (XP exercices + hardskill) */
  total_earned: number;
  /** Points dépensés */
  spent: number;
  /** Solde Points = gagné − dépensé */
  balance: number;
  /** Points de comportement gagnés (net) */
  behavior_earned?: number;
  /** Points de comportement dépensés */
  behavior_spent?: number;
  /** Solde Comportement */
  behavior_balance?: number;
  catalogs?: CatalogInfo[];
}
