/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Explorito - Application Éducative
 * OpenAPI spec version: 1.0.0
 */
import type { CatalogInfo } from "./catalogInfo";

/**
 * Porte-monnaie XP partagé + avancement par catalogue.
 */
export interface WalletSummary {
  /** XP total gagné (inchangé, pilote les niveaux) */
  total_earned: number;
  /** XP dépensé (tous catalogues confondus) */
  spent: number;
  /** XP dépensable = gagné − dépensé */
  balance: number;
  catalogs?: CatalogInfo[];
}
