"""add pokemon_unlocks

Revision ID: 2f655a5969cd
Revises: 7d97e5608e69
Create Date: 2026-07-24 11:51:18.136088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f655a5969cd'
down_revision: Union[str, Sequence[str], None] = '7d97e5608e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_unlocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pokemon_id', name='uq_user_pokemon')
    )
    op.create_index(op.f('ix_pokemon_unlocks_id'), 'pokemon_unlocks', ['id'], unique=False)
    op.create_index(op.f('ix_pokemon_unlocks_user_id'), 'pokemon_unlocks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_unlocks_user_id'), table_name='pokemon_unlocks')
    op.drop_index(op.f('ix_pokemon_unlocks_id'), table_name='pokemon_unlocks')
    op.drop_table('pokemon_unlocks')
    # ### end Alembic commands ###
